apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bigbang-app
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: bigbang/application-sets
    repoURL: "https://github.com/argo-universe/argo-bigbang"
    targetRevision: {{ .Values.targetRevision }}
    helm:
      parameters:
        - name: "env"
          value: {{ .Values.env }}
        - name: "targetRevision"
          value: {{ .Values.targetRevision }}          
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
