config:
  namespace: argocd

argo-cd:
  configs:
    timeout.reconciliation: 10s
    styles: |
      .nav-bar {
        background: linear-gradient(to bottom, #149431,#0ae13e);
      }  
  server:
    ingress:
      # -- Enable an ingress resource for the Argo CD server
      enabled: true
      # -- Additional ingress annotations
      annotations: 
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      # -- Additional ingress labels
      labels: {}
      # -- Defines which ingress controller will implement the resource
      ingressClassName: "nginx"

      # -- List of ingress hosts
      ## Argo Ingress.
      ## Hostnames must be provided if Ingress is enabled.
      ## Secrets must be manually created in the namespace
      hosts: 
        - argocd.muratakdeniz.com

      # -- List of ingress paths
      paths:
        - /
      # -- Ingress path type. One of `Exact`, `Prefix` or `ImplementationSpecific`
      pathType: Prefix
      # -- Additional ingress paths
      extraPaths: []
        # - path: /*
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: ssl-redirect
        #       port:
        #         name: use-annotation

      # -- Ingress TLS configuration
      tls: 
        - secretName: sampleapp.muratakdeniz.com
          hosts:
            - argocd.muratakdeniz.com

      # -- Uses `server.service.servicePortHttps` instead `server.service.servicePortHttp`
      https: true